Repository compucorp/uk.co.compucorp.civiawards, pull requests merged in 2020-11, with the labels that each got.

#145 RSE-1455: Fix Duplicate Workflow functionality
  ang/civiawards-workflow.ang.php
  ang/civiawards-workflow.js
  ang/civiawards-workflow/duplicate-workflow-applicant-management.service.js
  ang/test/civiawards-workflow/duplicate-workflow-applicant-management.service.spec.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/award-creation/directives/basic-details-form.directive.spec.js
  ang/test/civiawards/award-creation/directives/review-fields/review-fields-table.directive.spec.js
  ang/test/global.js
  ang/test/karma.conf.js
  ang/test/mocks/data/award-additional-details.data.js
  civiawards.php
Labels: bug

#146 RSE-1388: Rename 'Award Type' field to `Award Sub Type`
  CRM/CiviAwards/DAO/AwardDetail.php
  CRM/CiviAwards/DAO/AwardManager.php
  CRM/CiviAwards/DAO/AwardReviewPanel.php
  CRM/CiviAwards/Form/AwardCustomField.php
  CRM/CiviAwards/Helper/CaseTypeCategory.php
  CRM/CiviAwards/Helper/CustomGroupPostProcess.php
  CRM/CiviAwards/Service/ApplicantManagementAwardDetailPostProcessor.php
  CRM/CiviAwards/Service/ApplicantManagementCustomGroupDisplayFormatter.php
  CRM/CiviAwards/Setup/CreateAwardSubtypeOptionGroup.php
  CRM/CiviAwards/Setup/CreateAwardTypeOptionGroup.php
  CRM/CiviAwards/Uninstall/RemoveCustomGroupSupportForApplicantManagement.php
  CRM/CiviAwards/Upgrader.php
  CRM/CiviAwards/Upgrader/Steps/Step1007.php
  ang/civiawards.ang.php
  ang/civiawards/award-creation/directives/award.directive.js
  ang/civiawards/award-creation/directives/basic-details-form.directive.html
  ang/civiawards/award-creation/directives/basic-details-form.directive.js
  ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
  ang/civiawards/dashboard/directives/more-filters-popup.html
  ang/civiawards/shared/services/award-subtype.service.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/award-creation/directives/basic-details-form.directive.spec.js
  ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
  ang/test/civiawards/shared/services/award-subtype.service.spec.js
  ang/test/civiawards/shared/services/award-type.service.spec.js
  ang/test/mocks/data/award-additional-details.data.js
  ang/test/mocks/data/sub-type.data.js
  sql/auto_install.sql
  templates/CRM/CiviAwards/Form/AwardCustomField.tpl
  xml/schema/CRM/CiviAwards/AwardDetail.xml
Labels: new feature

#147 CPS-386: Release v1.0.0-beta.7
  info.xml
Labels: release

#153 RSE-1387: Display Is Template field
  ang/civiawards/award-creation/directives/award.directive.js
  ang/civiawards/award-creation/directives/basic-details-form.directive.html
  ang/civiawards/award-creation/directives/basic-details-form.directive.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/award-creation/directives/basic-details-form.directive.spec.js
  ang/test/mocks/data/award-additional-details.data.js
Labels: enhancement

#151 RSE-1404: Fix Contact Group limit
  ang/civiawards/shared/directives/contacts-group-dropdown.directive.js
Labels: bug

#152 RSE-1434: Review panel statuses
  ang/civiawards/award-creation/directives/award.directive.html
  ang/civiawards/award-creation/directives/award.directive.js
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
Labels: bug

#154 RSE-1277: Award Templates
  CRM/CiviAwards/DAO/AwardDetail.php
  CRM/CiviAwards/DAO/AwardManager.php
  CRM/CiviAwards/DAO/AwardReviewPanel.php
  CRM/CiviAwards/Upgrader/Steps/Step1008.php
  ang/civiawards/award-creation/directives/award.directive.js
  ang/civiawards/award-creation/directives/basic-details-form.directive.html
  ang/civiawards/award-creation/directives/basic-details-form.directive.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/award-creation/directives/basic-details-form.directive.spec.js
  ang/test/mocks/data/award-additional-details.data.js
  sql/auto_install.sql
  xml/schema/CRM/CiviAwards/AwardDetail.xml
Labels: enhancement

#158 CPS-397: Fix failing Drupal Build For Unit Test Workflow
  .github/workflows/unit-test.yml
Labels: bug
