Repository compucorp/uk.co.compucorp.civiawards, pull requests merged in 2020-06, with the labels that each got.

#97 RSE-1121: Release v1.0.0-beta.3
  info.xml
Labels: release

#99 RSE-1138: Exclude Groups Should Take Precedence For Panel Contacts Logic
  .github/workflows/unit-test.yml
  CRM/CiviAwards/Service/AwardPanelContact.php
  ang/test/karma.conf.js
  phpcs-ruleset.xml
  tests/phpunit/CRM/CiviAwards/Service/AwardPanelContactTest.php
Labels: enhancement

#102 RSE-1141: Hide 'Statuses' field In Review Panel popup when related checkbox is unticked
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
Labels: improvements

#101 RSE-841: Display tag colours on award review form header
  CRM/CiviAwards/Form/AwardReview.php
  ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
  ang/test/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.spec.js
Labels: improvements

#104 RSE-1139: Add AwardReveiewPanel.getReviewAcess API
  CRM/CiviAwards/Service/AwardApplicationContactAccess.php
  CRM/CiviAwards/Test/Fabricator/Case.php
  CRM/CiviAwards/Test/Fabricator/CaseType.php
  api/v3/AwardReviewPanel.php
  tests/phpunit/CRM/CiviAwards/Service/AwardApplicationContactAccessTest.php
Labels: enhancement

#108 RSE-982: Review Fields Popup UI Changes
  ang/civiawards/award-creation/directives/review-fields/review-field-selection.html
  ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.js
  ang/test/civiawards/award-creation/directives/review-fields/review-fields-table.directive.spec.js
Labels: improvements
