Repository compucorp/uk.co.compucorp.civiawards, pull requests merged in 2020-09, with the labels that each got.

#127 RSE-1096: Awards Instance support - Frontend solution
  ang/civiawards/app.routes.js
  ang/civiawards/award-creation/directives/award.directive.js
  ang/civiawards/dashboard/configs/case-type-items.config.js
  ang/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.js
  ang/civiawards/dashboard/directives/edit-award-button.controller.js
  ang/civiawards/dashboard/directives/edit-award-button.html
  ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
  ang/civiawards/reviews-tab/configs/add-reviews-tab.config.js
  ang/civiawards/shared/services/is-application-management-screen.factory.js
  ang/civiawards/shared/services/is-award-screen.factory.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.spec.js
  ang/test/civiawards/shared/services/ang/civiawards/shared/services/is-application-management-screen.factory.spec.js
Labels: new feature

#131 RSE-1118: Fix Permission Issues When Administering An Award
  CRM/CiviAwards/Hook/AlterAPIPermissions/Award.php
  CRM/CiviAwards/Service/ApplicantManagementMenu.php
Labels: bug

#133 RSE-1311: Fix SSP review and view applications pages to show correct CaseTags
  CRM/CiviAwards/Form/AwardReview.php
Labels: bug

#122 RSE-1118: Award Instance Build
  .github/workflows/linters.yml
  CRM/CiviAwards/Form/AwardCustomField.php
  CRM/CiviAwards/Helper/CaseTypeCategory.php
  CRM/CiviAwards/Hook/AlterAPIPermissions/Award.php
  CRM/CiviAwards/Service/ApplicantManagementMenu.php
  CRM/CiviAwards/Service/ApplicantManagementUtils.php
  CRM/CiviAwards/Setup/AddApplicantManagementCaseTypeCustomGroupSupport.php
  CRM/CiviAwards/Setup/AddApplicationManagementWordReplacement.php
  CRM/CiviAwards/Setup/CreateApplicantManagementOption.php
  CRM/CiviAwards/Setup/CreateAwardTypeOptionGroup.php
  CRM/CiviAwards/Setup/CreateAwardsMenus.php
  CRM/CiviAwards/Test/Fabricator/CaseCategory.php
  CRM/CiviAwards/Uninstall/RemoveCustomGroupSupportForApplicantManagement.php
  CRM/CiviAwards/Upgrader.php
  CRM/CiviAwards/Upgrader/Steps/Step1002.php
  CRM/CiviAwards/Upgrader/Steps/Step1003.php
  CRM/CiviAwards/Upgrader/Steps/Step1004.php
  CRM/CiviAwards/WordReplacement/ApplicantManagement.php
  ang/civiawards/app.routes.js
  ang/civiawards/award-creation/directives/award.directive.js
  ang/civiawards/dashboard/configs/case-type-items.config.js
  ang/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.js
  ang/civiawards/dashboard/directives/edit-award-button.controller.js
  ang/civiawards/dashboard/directives/edit-award-button.html
  ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
  ang/civiawards/reviews-tab/configs/add-reviews-tab.config.js
  ang/civiawards/shared/services/is-application-management-screen.factory.js
  ang/civiawards/shared/services/is-award-screen.factory.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.spec.js
  ang/test/civiawards/shared/services/ang/civiawards/shared/services/is-application-management-screen.factory.spec.js
  api/v3/AwardDetail.php
  config/word_replacement/applicant_management.php
  templates/CRM/CiviAwards/Form/AwardCustomField.tpl
  tests/phpunit/Api/v3/AwardDetailTest.php
  xml/Menu/civiawards.xml
Labels: new feature

#135 CPS-335: Release v1.0.0-beta.4
  info.xml
Labels: release

#132 RSE-1246: Disallow empty statuses if Panel can change the status of an application checkbox is ticked
  CRM/CiviAwards/BAO/AwardReviewPanel.php
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  css/civiawards.min.css
  css/civiawards.min.css.map
  scss/components/_award.scss
  tests/phpunit/CRM/CiviAwards/BAO/AwardReviewPanelTest.php
Labels: bug
