Repository compucorp/uk.co.compucorp.civiawards, pull requests merged in 2020-10, with the labels that each got.

#136 RSE-1393: Change Award Manager field label
  .github/workflows/unit-test.yml
  README.md
  ang/civiawards/award-creation/directives/basic-details-form.directive.html
Labels: new feature

#130 RSE-1296: Award Custom Field UI
  ang/civiawards/award-creation/directives/award-custom-field-sets.directive.html
  ang/civiawards/award-creation/directives/award-custom-field-sets.directive.js
  ang/civiawards/award-creation/directives/award.directive.html
  ang/civiawards/award-creation/directives/award.directive.js
  ang/test/civiawards/award-creation/directives/award-custom-field-sets.directive.spec.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/karma.conf.js
  css/civiawards.min.css
  css/civiawards.min.css.map
  scss/components/_custom-field-sets.scss
  templates/CRM/CiviAwards/Form/AwardCustomField.tpl
Labels: new feature

#138 CPS-360: Fix save award bug when there are no custom fields defined
  ang/civiawards/award-creation/directives/award-custom-field-sets.directive.js
  ang/test/civiawards/award-creation/directives/award-custom-field-sets.directive.spec.js
Labels: bug, regression

#139 RSE-1380: Add "Manage Workflows" Menu
  CRM/CiviAwards/Service/ApplicantManagementMenu.php
  CRM/CiviAwards/Setup/AddManageWorkflowMenu.php
  CRM/CiviAwards/Upgrader/Steps/Step1006.php
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
Labels: new feature

#142 RSE-1457: Fix Issue With Award Instance Custom Field Set Not Being Updated
  CRM/CiviAwards/Service/ApplicantManagementAwardDetailPostProcessor.php
Labels: bug

#144 CPS-375: Release v1.0.0-beta.6
  info.xml
Labels: release
