Repository compucorp/uk.co.compucorp.civiawards, pull requests merged in 2020-04, with the labels that each got.

#84 RSE-1052: Hide delete button when creating new panel
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
Labels: bug

#85 RSE-1051: Update Readme
  README.md
Labels: improvements

#83 RSE-1051: Release v1.0.0-beta.1
  README.md
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  info.xml
Labels: release

#90 ACU-68: Panel Application Status Restriction UI + Functionality
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  ang/test/mocks/data/review-panels.data.js
Labels: new feature

#91 ACU-32: Application Restricted Status
  CRM/CiviAwards/BAO/AwardReviewPanel.php
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  ang/test/mocks/data/review-panels.data.js
  tests/phpunit/CRM/CiviAwards/BAO/AwardReviewPanelTest.php
Labels: new feature

#87 RSE-898: Allow applications to be filtered by closed statuses.
  ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
  ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
Labels: bug

#89 RSE-1066: Add word replacements for clients
  config/word_replacement/awards_category.php
Labels: enhancement

#92 CPS-192: Release v1.0.0-beta.2
  info.xml
Labels: release
