Repository compucorp/uk.co.compucorp.civiawards, pull requests merged in 2020-03, with the labels that each got.

#62 RSE-670: Save Review Panel using API
  ang/civiawards/award-creation/directives/award.directive.html
  ang/civiawards/award-creation/directives/award.directive.js
  ang/civiawards/award-creation/directives/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels.directive.spec.js
  css/civiawards.min.css
  css/civiawards.min.css.map
  scss/components/_award.scss
Labels: new feature

#64 RSE-959: Move awards creation page to a new namespace
  CRM/CiviAwards/Page/AwardAngular.php
  ang/civiawards.ang.php
  ang/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.js
  ang/test/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.spec.js
  xml/Menu/civiawards.xml
Labels: bug, improvements

#65 RSE-868: Fix Table Column width for review tab
  ang/civiawards/award-creation/directives/review-fields-table.directive.html
  ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
Labels: improvements

#67 RSE-967: Do not apply More Filters in non awards dashboard
  ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
  ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
Labels: bug

#69 RSE-777: Fix Misc bugs
  ang/civiawards/award-creation/directives/review-panels.directive.js
  ang/civiawards/dashboard/directives/edit-award-button.html
  ang/test/civiawards/award-creation/directives/review-panels.directive.spec.js
Labels: bug

#68 RSE-678: Review Panel Group Selection UI + Functionality
  CRM/CiviAwards/BAO/AwardReviewPanel.php
  ang/civiawards/award-creation/directives/review-fields/review-field-selection.html
  ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.html
  ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.js
  ang/civiawards/award-creation/directives/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels.directive.js
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/civiawards/shared/directives/contacts-group-dropdown.directive.js
  ang/test/civiawards/award-creation/directives/review-fields/review-fields-table.directive.spec.js
  ang/test/civiawards/award-creation/directives/review-panels.directive.spec.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  css/civiawards.min.css
  css/civiawards.min.css.map
  scss/components/_award.scss
  scss/components/_contacts-group.scss
Labels: new feature

#72 RSE-672: Review Panel List UI + functionality
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  ang/test/mocks/data/review-panels.data.js
  css/civiawards.min.css
  css/civiawards.min.css.map
  scss/components/_award.scss
Labels: new feature

#73 RSE-671: Delete Review Panels + Enable/Disable from list
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  css/civiawards.min.css
  css/civiawards.min.css.map
  scss/components/_award.scss
Labels: new feature

#74 RSE-674: Add tabs and Application Status to Review Panel
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  ang/test/mocks/data/review-panels.data.js
Labels: new feature

#78 RSE-892: Fix HTML text formatting on the review table tab
  ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
  ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
Labels: bug

#79 RSE-654: Fix error when no Relationships are present in Review Panels
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  ang/test/mocks/data/review-panels.data.js
Labels: bug

#77 RSE-944: Fix API param value when case type id is null
  ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
  ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
Labels: bug

#76 RSE-675: Add tags Support to Review Panels
  .npmrc 
  .nvmrc
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  ang/test/mocks/data/review-panels.data.js
  css/civiawards.min.css
  css/civiawards.min.css.map
  package.json
  scss/components/_award.scss
Labels: new feature

#81 RSE-653: Set Permissions For Deleting Award Panels
  CRM/CiviAwards/Hook/AlterAPIPermissions/Award.php
Labels: bug

#82 Merging Awards Sprint 5 to Master
  .npmrc 
  .nvmrc
  CRM/CiviAwards/BAO/AwardReviewPanel.php
  CRM/CiviAwards/Hook/AlterAPIPermissions/Award.php
  ang/civiawards/award-creation/directives/review-fields/review-field-selection.html
  ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.html
  ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.js
  ang/civiawards/award-creation/directives/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels.directive.html
  ang/civiawards/award-creation/directives/review-panels.directive.js
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.html
  ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
  ang/civiawards/shared/directives/contacts-group-dropdown.directive.js
  ang/test/civiawards/award-creation/directives/review-fields/review-fields-table.directive.spec.js
  ang/test/civiawards/award-creation/directives/review-panels.directive.spec.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  ang/test/mocks/data/review-panels.data.js
  css/civiawards.min.css
  css/civiawards.min.css.map
  package.json
  scss/components/_award.scss
  scss/components/_contacts-group.scss
Labels: new feature

#71 RSE-905: Case Category Custom Fields
  CRM/CiviAwards/Setup/AddAwardsCgExtendsOptionValue.php
  CRM/CiviAwards/Setup/DeleteAwardsCgExtendsOption.php
  CRM/CiviAwards/Setup/ProcessAwardsCategoryForCustomGroupSupport.php
  CRM/CiviAwards/Uninstall/RemoveCustomGroupSupportForAwardsCategory.php
  CRM/CiviAwards/Upgrader.php
Labels: improvements

#80 RSE-956: Define award activity types
  ang/civiawards/activity-forms/services/review-form.service.js
  ang/civiawards/award-creation/directives/award.directive.js
  ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
  ang/test/civiawards/activity-forms/services/review-form.service.spec.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.spec.js
  civiawards.php
Labels: enhancement
