Repository compucorp/uk.co.compucorp.civiawards, pull requests merged in 2021-04, with the labels that each got.

#215 CPS-487: Capitalize Category Name on Label Menu
  CRM/CiviAwards/Service/ApplicantManagementMenu.php
Labels: enhancement

#217 CATL-1660: Update NodeJS to v14.16.0 & HTML Linter
  .github/workflows/linters.yml
  .github/workflows/unit-test.yml
  .htmlhintrc
  .lintstagedrc
  .nvmrc
  ang/civiawards-workflow/filters/directives/workflow-list-filter-is-active.html
  ang/civiawards-workflow/filters/directives/workflow-list-filter-is-template.html
  ang/civiawards/award-creation/directives/award-stages-table.directive.html
  ang/civiawards/award-creation/directives/basic-details-form.directive.html
  ang/civiawards/award-creation/directives/review-fields/review-field-selection.html
  ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.html
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
  ang/civiawards/reviews-tab/services/reviews-case-tab-placeholder.html
  package-lock.json
  package.json
Labels: enhancement

#222 CPS-556: Fix unit tests
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
Labels: bug

#219 CPS-202: Allow Long Case Category Names For Menus
  CRM/CiviAwards/Service/ApplicantManagementMenu.php
  CRM/CiviAwards/Setup/AddManageWorkflowMenu.php
  CRM/CiviAwards/Upgrader/Steps/Step1011.php
  ang/civiawards/award-creation/directives/award.directive.html
  ang/civiawards/award-creation/directives/award.directive.js
  ang/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.js
  ang/civiawards/dashboard/directives/edit-award-button.controller.js
  ang/test/civiawards-base/services/is-application-management-screen.factory.spec.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.spec.js
  ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
  ang/test/civiawards/reviews-tab/configs/add-reviews-tab.config.spec.js
Labels: improvements
