Repository compucorp/uk.co.compucorp.civiawards, pull requests merged in 2021-03, with the labels that each got.

#204 RSE-1202: Update Panel relationship label
  ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
Labels: improvements

#207 CPS-471: Release v1.0.0-beta.12
  info.xml
Labels: release

#209 CPS-464: Add Github Action to Automate Release Pull Request Creation
  .github/workflows/release-pr.yml
Labels: new feature

#211 ACU-519: Update Awards Payment Activity Status Labels
  CRM/CiviAwards/Setup/UpdateAwardPaymentActivityStatusLabel.php
  CRM/CiviAwards/Upgrader.php
  CRM/CiviAwards/Upgrader/Steps/Step1010.php
Labels: improvements

#212 ACU-539: Add Clear Filter button to Payments tab
  ang/civiawards-payments-tab/directives/payment-filters.directive.html
  ang/civiawards-payments-tab/directives/payment-filters.directive.js
  ang/civiawards-payments-tab/directives/payments-case-tab-actions.directive.js
  ang/civiawards-payments-tab/directives/payments-case-tab-add-payment.directive.js
  ang/civiawards-workflow/action-links/controllers/workflow-advanced.controller.js
  ang/civiawards/activity-forms/services/review-form.service.js
  ang/civiawards/dashboard/configs/case-type-items.config.js
  ang/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.js
  ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
  ang/test/.eslintrc.json
  ang/test/civiawards-base/services/applicant-management-workflow.service.spec.js
  ang/test/civiawards-base/services/award-subtype.service.spec.js
  ang/test/civiawards-base/services/is-application-management-screen.factory.spec.js
  ang/test/civiawards-payments-tab/configs/add-payments-tab.config.spec.js
  ang/test/civiawards-payments-tab/directives/payment-filters.directive.spec.js
  ang/test/civiawards-payments-tab/directives/payments-case-tab-actions.directive.spec.js
  ang/test/civiawards-payments-tab/directives/payments-case-tab-add-payment.directive.spec.js
  ang/test/civiawards-payments-tab/directives/payments-table.directive.spec.js
  ang/test/civiawards-payments-tab/services/awards-payment-activity-status.service.spec.js
  ang/test/civiawards-payments-tab/services/payments-case-tab.service.spec.js
  ang/test/civiawards-workflow/action-links/controlers/workflow-advanced.controller.spec.js
  ang/test/civiawards-workflow/filters/controllers/workflow-filter.controller.spec.js
  ang/test/civiawards/activity-forms/activity-forms.config.spec.js
  ang/test/civiawards/activity-forms/services/review-form.service.spec.js
  ang/test/civiawards/award-creation/directives/award-custom-field-sets.directive.spec.js
  ang/test/civiawards/award-creation/directives/award-stages-table.directive.spec.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/award-creation/directives/basic-details-form.directive.spec.js
  ang/test/civiawards/award-creation/directives/review-fields/review-fields-table.directive.spec.js
  ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
  ang/test/civiawards/dashboard/configs/awards-dashboard-action-items.config.spec.js
  ang/test/civiawards/dashboard/configs/case-type-items.config.spec.js
  ang/test/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.spec.js
  ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
  ang/test/civiawards/reviews-tab/configs/add-reviews-tab.config.spec.js
  ang/test/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.spec.js
  ang/test/civiawards/shared/services/can-create-or-edit-awards.factory.spec.js
  ang/test/global.js
  gulp-tasks/sass.js
Labels: enhancement

#214 ACU-545: Payments form fix for Activity Feed
  ang/civiawards-payments-tab/directives/payments-case-tab-actions.directive.js
  ang/civiawards-payments-tab/services/payments-activity-form.service.js
  ang/civiawards/activity-forms/activity-forms.config.js
  ang/civiawards/activity-forms/services/review-activity-form.service.js
  ang/civiawards/award-creation/directives/award-custom-field-sets.directive.js
  ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
  ang/test/civiawards-payments-tab/mocks/data/payments.data.js
  ang/test/civiawards-payments-tab/services/payments-activity-form.service.spec.js
  ang/test/civiawards/activity-forms/services/review-activity-form.service.spec.js
  ang/test/civiawards/award-creation/directives/award-custom-field-sets.directive.spec.js
  ang/test/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.spec.js
  api/v3/FinanceManagement.php
  css/civiawards.min.css
  css/civiawards.min.css.map
  scss/components/_activity-panel.scss
  scss/components/_payments-form.scss
  templates/CRM/CiviAwards/Form/AwardPayment.tpl
Labels: bug

#208 CPS-427: Civiawards alignment with CiviCRM 5.35
  .github/workflows/unit-test.yml
  CRM/CiviAwards/BAO/AwardReviewPanel.php
  CRM/CiviAwards/Upgrader/Base.php
  ang/civiawards-base.ang.php
  ang/civiawards-payments-tab.ang.php
  ang/civiawards-workflow.ang.php
  ang/civiawards.ang.php
  civiawards.civix.php
  phpcs-ruleset.xml
Labels: bug, improvements
