Repository compucorp/uk.co.compucorp.civiawards, pull requests merged in 2021-02, with the labels that each got.

#181 CPS-449: Release v1.0.0-beta.10
  info.xml
Labels: release

#180 RSE-1295: Fix Create/Edit Award Redirection
  ang/civiawards-workflow/services/applicant-management-workflow.service.js
  ang/civiawards/app.routes.js
  ang/civiawards/award-creation/directives/award.directive.html
  ang/civiawards/award-creation/directives/award.directive.js
  ang/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.js
  ang/civiawards/dashboard/directives/edit-award-button.controller.js
  ang/test/civiawards-workflow/services/applicant-management-workflow.service.spec.js
  ang/test/civiawards/award-creation/directives/award.directive.spec.js
  ang/test/civiawards/dashboard/configs/case-type-items.config.spec.js
  ang/test/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.spec.js
Labels: improvements

#174 RSE-1620: Fix Award Custom Fields Leakage Bug
  CRM/CiviAwards/Service/ApplicantManagementCustomGroupPostProcessor.php
  tests/phpunit/CRM/CiviAwards/Service/ApplicantManagementCustomGroupPostProcessorTest.php
Labels: bug

#182 ACU-422: Payments Tab
  CRM/CiviAwardsPaymentsTab/Hook/AddCiviCaseDependentAngularModules/PaymentsTabModule.php
  ang/civiawards-payments-tab.ang.php
  ang/civiawards-payments-tab.js
  ang/civiawards-payments-tab/configs/add-payments-tab.config.js
  ang/civiawards-payments-tab/directives/payments-case-tab-content.directive.html
  ang/civiawards-payments-tab/directives/payments-case-tab-content.directive.js
  ang/civiawards-payments-tab/services/payments-case-tab-content.html
  ang/civiawards-payments-tab/services/payments-case-tab.service.js
  ang/test/civiawards-payments-tab/configs/add-payments-tab.config.spec.js
  ang/test/civiawards-payments-tab/services/payments-case-tab.service.spec.js
  ang/test/global.js
  ang/test/karma.conf.js
  civiawards.php
  tests/phpunit/CRM/CiviAwardsPaymentsTab/Hook/AddCiviCaseDependentAngularModules/PaymentsTabModuleTest.php
Labels: enhancement

#184 ACU-493: Display payments info on the payments tab
  ang/civiawards-payments-tab.ang.php
  ang/civiawards-payments-tab/constants/payment-types.constant.js
  ang/civiawards-payments-tab/directives/payments-case-tab-content.directive.html
  ang/civiawards-payments-tab/directives/payments-case-tab-content.directive.js
  ang/civiawards-payments-tab/directives/payments-table.directive.html
  ang/civiawards-payments-tab/directives/payments-table.directive.js
  ang/civiawards-payments-tab/services/payments-case-tab-content.html
  ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
  ang/test/civiawards-payments-tab/directives/payments-table.directive.spec.js
  ang/test/civiawards-payments-tab/mocks/data/custom-fields.data.js
  ang/test/civiawards-payments-tab/mocks/data/payment-types.data.js
  ang/test/civiawards-payments-tab/mocks/data/payments.data.js
  ang/test/civiawards-payments-tab/mocks/modules.mock.js
  ang/test/global.js
  ang/test/karma.conf.js
  css/civiawards.min.css
  css/civiawards.min.css.map
  gulp-tasks/karma-unit-test.js
  gulpfile.js
  scss/components/_reviews-tab.scss
Labels: enhancement

#186 ACU-494: Add payment filters to the payment tab
  ang/civiawards-payments-tab/directives/payment-filters.directive.html
  ang/civiawards-payments-tab/directives/payment-filters.directive.js
  ang/civiawards-payments-tab/directives/payments-table.directive.html
  ang/civiawards-payments-tab/directives/payments-table.directive.js
  ang/test/civiawards-payments-tab/directives/payment-filters.directive.spec.js
  ang/test/civiawards-payments-tab/directives/payments-table.directive.spec.js
  ang/test/civiawards-payments-tab/mocks/data/payment-statuses.data.js
  css/civiawards.min.css
  css/civiawards.min.css.map
  scss/components/_payments-tab.scss
Labels: enhancement

#188 ACU-495: Add payments pagination support
  ang/civiawards-payments-tab/directives/payments-table.directive.html
  ang/civiawards-payments-tab/directives/payments-table.directive.js
  ang/test/civiawards-payments-tab/directives/payments-table.directive.spec.js
Labels: enhancement

#190 ACU-507: Fix Payment Amounts column
  ang/civiawards-payments-tab/directives/payments-table.directive.html
  ang/civiawards-payments-tab/directives/payments-table.directive.js
Labels: bug

#192 ACU-505: Remove Configuration Cog for Payment Currency
  CRM/CiviAwards/Form/AwardPayment.php
Labels: enhancement

#193 ACU-524: Add Attachments For Award Payments Form
  CRM/CiviAwards/Form/AwardPayment.php
  css/civiawards.min.css
  css/civiawards.min.css.map
  scss/civiawards.scss
  scss/components/_payments-form.scss
  templates/CRM/CiviAwards/Form/AwardPayment.tpl
Labels: enhancement

#196 ACU-527: Make "Awards Payment Bank Details" custom fields searchable and naming consistency fix
  xml/custom_fields/payment_bank_details_install.xml
Labels: improvements

#194 ACU-518: Fix payment status types
  CRM/CiviAwards/Setup/CreateAwardPaymentActivityTypes.php
Labels: bug

#197 ACU-528: Fix Payment form styles
  css/civiawards.min.css
  css/civiawards.min.css.map
  scss/components/_payments-form.scss
  templates/CRM/CiviAwards/Form/AwardPayment.tpl
Labels: improvements

#200 CPS-466: Release v1.0.0-beta.11
  info.xml
Labels: release

#177 RSE-1588: Add Pagination to Manage Workflow and Dashboard Page + New Apis
  CRM/CiviAwards/Event/Listener/AwardCaseFilter.php
  CRM/CiviAwards/Hook/AlterAPIPermissions/Award.php
  CRM/CiviAwards/Service/AwardCaseFilterPreProcess.php
  ang/civiawards-base/services/applicant-management-workflow.service.js
  ang/civiawards-workflow/configs/application-management-workflow-list-filters.config.js
  ang/civiawards-workflow/filters/controllers/workflow-filter.controller.js
  ang/civiawards-workflow/filters/directives/workflow-list-filter-is-template.html
  ang/civiawards-workflow/filters/directives/workflow-list-filter-manager.html
  ang/civiawards-workflow/filters/directives/workflow-list-filter-subtype.html
  ang/civiawards-workflow/services/applicant-management-workflow.service.js
  ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
  ang/civiawards/dashboard/directives/more-filters-popup.html
  ang/test/civiawards-base/services/applicant-management-workflow.service.spec.js
  ang/test/civiawards-workflow/filters/controllers/workflow-filter.controller.spec.js
  ang/test/civiawards-workflow/services/applicant-management-workflow.service.spec.js
  ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
  api/v3/Award.php
  civiawards.php
Labels: bug, enhancement, improvements, new feature

#203 ACU-535: Fix Disabled Payment Fields
  CRM/CiviAwards/Form/AwardPayment.php
  js/award-payment-form.js
Labels: bug

#202 ACU-537: Handle missing payment data
  CRM/CiviAwards/Form/AwardPayment.php
  ang/civiawards-payments-tab/directives/payments-table.directive.js
  ang/test/civiawards-payments-tab/directives/payments-table.directive.spec.js
  js/award-payment-form.js
Labels: bug

#187 CPS-443: Sync Log Tables In Base Upgrader
  CRM/CiviAwards/Upgrader.php
  CRM/CiviAwards/Upgrader/Steps/Step1007.php
  CRM/CiviAwards/Upgrader/Steps/Step1008.php
Labels: improvements
