Repository compucorp/uk.co.compucorp.civiawards, pull requests merged in 2021-01, with the labels that each got.

#160 RSE-1554: Applicant Management edit workflow link
  ang/civiawards-workflow/services/applicant-management-workflow.service.js
  ang/test/civiawards-workflow/services/applicant-management-workflow.service.spec.js
Labels: new feature

#166 RSE-1231: Fix Bug In Review Field Reordering
  CRM/CiviAwards/Helper/ApplicantReview.php
  CRM/CiviAwards/Service/AwardProfile.php
  tests/phpunit/CRM/CiviAwards/Service/AwardProfileTest.php
Labels: bug

#165 RSE-1572: Fix Custom Fields Issue On Awards
  CRM/CiviAwards/Helper/CaseTypeCategory.php
Labels: bug

#167 RSE-1600: Implement "Advanced" Action Dropdown
  ang/civiawards-workflow/action-links/controllers/workflow-advanced.controller.js
  ang/civiawards-workflow/action-links/directives/workflow-list-advanced-action.html
  ang/civiawards-workflow/configs/application-management-workflow-list-action-items.config.js
  ang/test/civiawards-workflow/action-links/controlers/workflow-advanced.controller.spec.js
Labels: new feature

#168 CPS-438: Release v1.0.0-beta.9
  info.xml
Labels: release

#172 RSE-1597: Block reviews for disabled applications
  ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
  ang/test/civiawards/dashboard/configs/case-type-items.config.spec.js
  ang/test/mocks/configs/awards-case-types.config.js
  ang/test/mocks/data/award.data.js
Labels: improvements

#169 RSE-1034: Add filter to display disabled awards and applications
  ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
  ang/civiawards/dashboard/directives/more-filters-popup.html
  ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
Labels: enhancement

#178 RSE-1627: Fix award filter notifications
  ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
  ang/civiawards/dashboard/directives/more-filters-popup.html
  ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
Labels: bug, improvements

#173 RSE-881: Show disabled applications
  ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
  ang/civiawards/dashboard/directives/more-filters-popup.html
  ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
  ang/test/civiawards/dashboard/configs/case-type-items.config.spec.js
  ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
  ang/test/mocks/configs/awards-case-types.config.js
  ang/test/mocks/data/award.data.js
Labels: new feature

#164 CPS-411: Import awards using CSV importer extension
  CRM/CiviAwards/Api/Wrapper/AwardDetailExtraFields.php
  CRM/CiviAwards/BAO/AwardDetail.php
  CRM/CiviAwards/Service/AwardImport.php
  api/v3/AwardImport.php
  tests/phpunit/CRM/CiviAwards/Service/AwardImportTest.php
Labels: enhancement

#176 CPS-423: Sync Log Tables With Actual Tables While Running Upgraders
  CRM/CiviAwards/Upgrader/Steps/Step1007.php
  CRM/CiviAwards/Upgrader/Steps/Step1008.php
Labels: bug
